# -*- coding: utf-8 -*-
"""personal_intro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N-ZghpDea6PQmO6tyZOrqniFM4b4Ugzy
"""

#-------------Personal Introduction Program ---------------#
name = input("What is your name?")

age = input("What is your age?")

hobby = input("What is your favourite hobby?")

print(f"Welcome {name}!")
print(f"You are {age} years old who loves {hobby}.")